apiVersion: v1
kind: Service
metadata:
  name: odoo-lb-service
spec:
  type: LoadBalancer
  selector:
    app: odoo-erp
    department: vet
  ports:
    - protocol: TCP
      port: 40000
      targetPort: 30000
