apiVersion: v1
kind: Service
metadata:
  name: web-interface
spec:
  type: LoadBalancer
  selector:
    app: web-ui
    department: vet-service
  ports:
    - protocol: TCP
      port: 60001
      targetPort: 50002
